# This file was generated by GoReleaser. DO NOT EDIT.
cask "althosts" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "20f637a212385c3b6c220583f0b3490651619e390192438e05a17325eb47304d"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_macOS_x86_64.zip"
    end
    on_arm do
      sha256 "c4e7dc0647620aa9057cc6fa30b069a2cfc073854e8b2b17253eb8e1fe776de4"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_macOS_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "bff7cce981a57effbf7294542b93f3e4312966592501b5a3d318fc9f7146fff8"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_Linux_x86_64.zip"
    end
    on_arm do
      sha256 "4d7047b0299f8a4646defa9f86976c6acf6a0c2d6fcdac8d9e9d6e709b771bba"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_Linux_arm64.zip"
    end
  end

  name "althosts"
  desc "althosts is a small CLI that manages multiple local /etc/hosts profiles and switches between them on demand. Everything stays local — no remote sync, daemons, or GUI."
  homepage "https://github.com/xshoji/althosts"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "althosts"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/althosts"]
    end
  end

  # No zap stanza required

end
