# This file was generated by GoReleaser. DO NOT EDIT.
cask "althosts" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/althosts"]
    end
  end

  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "681ff0222450d50acbadd094b40d8d812cd4c376c23d1cd9f07b685b0b9391d1"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_macOS_arm64.zip"
    end
    on_intel do
      sha256 "55fb10ed67174904b80c991c44a87011ca119e8e1fc2f93d6b67f8b90c7e2931"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_macOS_x86_64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "142c8b8dd4eb098ea5ebba44f391d010f0db48706fcc04b2d123567671cb441a"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_Linux_arm64.zip"
    end
    on_intel do
      sha256 "1402428689a8f18a8d45170644eed9d9cc53be3f381aedeaa1161552534dfd1b"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_Linux_x86_64.zip"
    end
  end

  name "althosts"
  desc "althosts is a small CLI that manages multiple local /etc/hosts profiles and switches between them on demand. Everything stays local — no remote sync, daemons, or GUI."
  homepage "https://github.com/xshoji/althosts"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "althosts"

  # No zap stanza required
end
