# This file was generated by GoReleaser. DO NOT EDIT.
cask "althosts" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "ed4bd9235af6a029b96cdf8ddd5d720ae03a49ebd88d3c8931d93f28dc95f8d7"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_macOS_x86_64.zip"
    end
    on_arm do
      sha256 "aabcc9a2fa581a322239df2e92ff1e08eb42bb83bd5a28344c6d5ffa937d78be"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_macOS_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "45ec8bbe8d9f6d6ccfcbb7370d06fc3448ee2b0e3a8a95760e41f3ca96ea76e1"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_Linux_x86_64.zip"
    end
    on_arm do
      sha256 "b79dceae70f5aac3873d315b0293f6829da2bd4220ebf7a16734e6d37bcfe0ca"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_Linux_arm64.zip"
    end
  end

  name "althosts"
  desc "althosts is a small CLI that manages multiple local /etc/hosts profiles and switches between them on demand. Everything stays local — no remote sync, daemons, or GUI."
  homepage "https://github.com/xshoji/althosts"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "althosts"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/althosts"]
    end
  end

  # No zap stanza required

end
