# This file was generated by GoReleaser. DO NOT EDIT.
cask "ek" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "8f83bbaa866e39a3a6d39d5fa6aac8cf26c2e926694ce00cc3fed348fc2ac9a9"
      url "https://github.com/xshoji/go-encrypted-text-kvs/releases/download/#{version}/go-encrypted-text-kvs_#{version}_macOS_x86_64.zip"
    end
    on_arm do
      sha256 "00342b911c6ff2d18badd8de3b87b073176497d3556a48232d6d311f022e3096"
      url "https://github.com/xshoji/go-encrypted-text-kvs/releases/download/#{version}/go-encrypted-text-kvs_#{version}_macOS_arm64.zip"
    end
  end

  name "ek"
  desc "ek is a small CLI tool for storing text key-value pairs in an encrypted local file."
  homepage "https://github.com/xshoji/go-encrypted-text-kvs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ek"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/ek"]
    end
  end

  # No zap stanza required

end
