# This file was generated by GoReleaser. DO NOT EDIT.
cask "ek" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "fa47b9cc980e3290b1d9abd47292ca289992eae43b3cb2677530e70ac788504d"
      url "https://github.com/xshoji/go-encrypted-text-kvs/releases/download/#{version}/go-encrypted-text-kvs_#{version}_macOS_x86_64.zip"
    end
    on_arm do
      sha256 "f8d9aa5aa55b29083c433553771a50946feef091386a633818b9b6ac455a4a19"
      url "https://github.com/xshoji/go-encrypted-text-kvs/releases/download/#{version}/go-encrypted-text-kvs_#{version}_macOS_arm64.zip"
    end
  end

  name "ek"
  desc "ek is a small CLI tool for storing text key-value pairs in an encrypted local file."
  homepage "https://github.com/xshoji/go-encrypted-text-kvs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ek"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/ek"]
    end
  end

  # No zap stanza required

end
