# This file was generated by GoReleaser. DO NOT EDIT.
cask "ek" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/ek"]
    end
  end

  version "0.0.2"

  on_macos do
    on_arm do
      sha256 "08086c375b52d8bedf4c79350af16d43dc554e11b39cabb0e73581527aa24f81"
      url "https://github.com/xshoji/go-encrypted-text-kvs/releases/download/#{version}/go-encrypted-text-kvs_#{version}_macOS_arm64.zip"
    end
    on_intel do
      sha256 "02523badd710fa67cf0c89d2c84c947ddd9823b4475c82862edfde23cbdced13"
      url "https://github.com/xshoji/go-encrypted-text-kvs/releases/download/#{version}/go-encrypted-text-kvs_#{version}_macOS_x86_64.zip"
    end
  end

  name "ek"
  desc "ek is a small CLI tool for storing text key-value pairs in an encrypted local file."
  homepage "https://github.com/xshoji/go-encrypted-text-kvs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ek"

  # No zap stanza required
end
