# This file was generated by GoReleaser. DO NOT EDIT.
cask "sesnap" do
  version "0.2.3"

  on_macos do
    on_arm do
      sha256 "7b369cf63086a58d61bc6763fc55b4b4d09a338417dbc838fa6f64da27da1d23"
      url "https://github.com/xshoji/sesnap/releases/download/v#{version}/sesnap_#{version}_macOS_arm64.zip"
    end
    on_intel do
      sha256 "847ce25cbc53df464bc3e8f34051932821a3c76aa1c5ba819054182eff3dc724"
      url "https://github.com/xshoji/sesnap/releases/download/v#{version}/sesnap_#{version}_macOS_x86_64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "b3e2a5c477f08cfe9d206dc4589a8293cebe9160d7faeae3d5a377993c792254"
      url "https://github.com/xshoji/sesnap/releases/download/v#{version}/sesnap_#{version}_Linux_arm64.zip"
    end
    on_intel do
      sha256 "990ddb070d15926b707e2b0d4045c2f4349e451682d2914d102d3a040da82e34"
      url "https://github.com/xshoji/sesnap/releases/download/v#{version}/sesnap_#{version}_Linux_x86_64.zip"
    end
  end

  name "sesnap"
  desc "A web page screenshot tool with parallel multi-URL capture and lock-free Chrome profile support, powered by chromedp (headless Chrome). Only Chrome is required — no Puppeteer, no Playwright, no Node.js, no Python."
  homepage "https://github.com/xshoji/sesnap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sesnap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/sesnap"]
    end
  end

  # No zap stanza required
end
