# This file was generated by GoReleaser. DO NOT EDIT.
cask "sesnap" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "91c67b4fee5e37f96d1585381ff7da29e13b9b59866007744fe0baa39eb26a03"
      url "https://github.com/xshoji/sesnap/releases/download/v#{version}/sesnap_#{version}_macOS_arm64.zip"
    end
    on_intel do
      sha256 "8ca8f10c09dea28136f46678a56cf0a4e3424e4d763983508ff1fcd0dc19df3e"
      url "https://github.com/xshoji/sesnap/releases/download/v#{version}/sesnap_#{version}_macOS_x86_64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "16c23bdf9972206a6f893664f7128308b9d171338d1d1faed7d74b681ad5b2b3"
      url "https://github.com/xshoji/sesnap/releases/download/v#{version}/sesnap_#{version}_Linux_arm64.zip"
    end
    on_intel do
      sha256 "bd4f6bc029ccfe3e5f49c99572ed2b4f8fb7a00dc04c9898ea679f6e875bb05d"
      url "https://github.com/xshoji/sesnap/releases/download/v#{version}/sesnap_#{version}_Linux_x86_64.zip"
    end
  end

  name "sesnap"
  desc "A web page screenshot tool with parallel multi-URL capture and lock-free Chrome profile support, powered by chromedp (headless Chrome). Only Chrome is required — no Puppeteer, no Playwright, no Node.js, no Python."
  homepage "https://github.com/xshoji/sesnap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sesnap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/sesnap"]
    end
  end

  # No zap stanza required
end
