# This file was generated by GoReleaser. DO NOT EDIT.
cask "sesnap" do
  version "0.2.3"

  on_macos do
    on_arm do
      sha256 "308399de7ffc59c83b03d9f56b8f0b74df46ac26f270b71d594d75d6d271fe12"
      url "https://github.com/xshoji/sesnap/releases/download/v#{version}/sesnap_#{version}_macOS_arm64.zip"
    end
    on_intel do
      sha256 "dc4e5e31a2f4340605fac1aed762c787a40a4575ba3c4a19f504b4bd913eb3b5"
      url "https://github.com/xshoji/sesnap/releases/download/v#{version}/sesnap_#{version}_macOS_x86_64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "cce3f2da37445baf05e7893b765f67ee2304c64a520eb1a60f41e6212a6a6011"
      url "https://github.com/xshoji/sesnap/releases/download/v#{version}/sesnap_#{version}_Linux_arm64.zip"
    end
    on_intel do
      sha256 "98898f9919b65a7ffcc36fa7e58e0d6481269a81ac69d05bd7b68362581f1133"
      url "https://github.com/xshoji/sesnap/releases/download/v#{version}/sesnap_#{version}_Linux_x86_64.zip"
    end
  end

  name "sesnap"
  desc "A web page screenshot tool with parallel multi-URL capture and lock-free Chrome profile support, powered by chromedp (headless Chrome). Only Chrome is required — no Puppeteer, no Playwright, no Node.js, no Python."
  homepage "https://github.com/xshoji/sesnap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sesnap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/sesnap"]
    end
  end

  # No zap stanza required
end
