# This file was generated by GoReleaser. DO NOT EDIT.
cask "althosts" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "7503e3d8460a22db612242f153ee3de47b331a4af74d3f280955284db14f48be"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_macOS_x86_64.zip"
    end
    on_arm do
      sha256 "c7bf708d8bc2a20ec517f7b5a2b6c36c73d6bac5d2e159a4fa16a1b4deefdabb"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_macOS_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "230bb28113c80def928aeeb793557b368b3276193da3d190368529cfd37d449d"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_Linux_x86_64.zip"
    end
    on_arm do
      sha256 "546c1f06b74d9a7f477e9a4f8c5c5e650738ff64cbd3057306e436bf8a7b2c24"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_Linux_arm64.zip"
    end
  end

  name "althosts"
  desc "althosts is a small CLI that manages multiple local /etc/hosts profiles and switches between them on demand. Everything stays local — no remote sync, daemons, or GUI."
  homepage "https://github.com/xshoji/althosts"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "althosts"

  # No zap stanza required

end
