# This file was generated by GoReleaser. DO NOT EDIT.
cask "althosts" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "9cec38261b73967cb90b4806cd7405dab887b8bdfbe799ecdc3a7c6f2eda084b"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_macOS_x86_64.zip"
    end
    on_arm do
      sha256 "9add5c2a36f9e62881094749062166f94646f0fa8577324c7b72a3f8a182d3e8"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_macOS_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "7278061d756de696f54ce4e6f358a6671c627b97dbc9f4ebf16ecd9a114f888b"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_Linux_x86_64.zip"
    end
    on_arm do
      sha256 "3ea709880d9587d80e77bc44b47c9f7aca01827430e47419ef60067a7eb925a0"
      url "https://github.com/xshoji/althosts/releases/download/#{version}/althosts_#{version}_Linux_arm64.zip"
    end
  end

  name "althosts"
  desc "althosts is a small CLI that manages multiple local /etc/hosts profiles and switches between them on demand. Everything stays local — no remote sync, daemons, or GUI."
  homepage "https://github.com/xshoji/althosts"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "althosts"

  # No zap stanza required

end
