# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cdpss < Formula
  desc "A web page screenshot tool with parallel multi-URL capture and lock-free Chrome profile support, powered by chromedp (headless Chrome). Only Chrome is required — no Puppeteer, no Playwright, no Node.js, no Python."
  homepage "https://github.com/xshoji/chromedp-screenshots"
  version "0.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.0/chromedp-screenshots_0.0.0_macOS_x86_64.zip"
      sha256 "4ff45e485658bd06560ee78efc7bf9560c182b27e5eafaf49dae09ede53af87d"

      define_method(:install) do
        bin.install "cdpss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.0/chromedp-screenshots_0.0.0_macOS_arm64.zip"
      sha256 "65cc57a35cdd9f092e7a0e662bcf46b4568abb4f95a3b02367ba94f8a9c6db37"

      define_method(:install) do
        bin.install "cdpss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.0/chromedp-screenshots_0.0.0_Linux_x86_64.zip"
      sha256 "926561c876232c3e63275d888bf8284853c2ddfdc6259976564e75ae1d40c32b"
      define_method(:install) do
        bin.install "cdpss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.0/chromedp-screenshots_0.0.0_Linux_arm64.zip"
      sha256 "ecb1dcd590e82aa0ad28d5786d173d5fe24226c78c6e762a73f5bb31fd579c54"
      define_method(:install) do
        bin.install "cdpss"
      end
    end
  end
end
