# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cdpss < Formula
  desc "A web page screenshot tool with parallel multi-URL capture and lock-free Chrome profile support, powered by chromedp (headless Chrome). Only Chrome is required — no Puppeteer, no Playwright, no Node.js, no Python."
  homepage "https://github.com/xshoji/chromedp-screenshots"
  version "0.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.0/chromedp-screenshots_0.0.0_macOS_x86_64.zip"
      sha256 "f9398a02f6fe17e0d473b4780ed30191a2a1bbe27e0e2adb7af60481c44c7306"

      define_method(:install) do
        bin.install "cdpss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.0/chromedp-screenshots_0.0.0_macOS_arm64.zip"
      sha256 "ae2352a85fbe4fc6ddb9ed76de6c3ebc9626da0499fbcc99ae221d91c5ff6af9"

      define_method(:install) do
        bin.install "cdpss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.0/chromedp-screenshots_0.0.0_Linux_x86_64.zip"
      sha256 "11a5384776ef2b1d6a8ae4a46f3f719d6e09ea71f4583331df778ccfa8a59b2d"
      define_method(:install) do
        bin.install "cdpss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.0/chromedp-screenshots_0.0.0_Linux_arm64.zip"
      sha256 "0208ddbe23df6a55c8e8d2997c5a318ca48bec2e3325a34f93a2f384f2983e55"
      define_method(:install) do
        bin.install "cdpss"
      end
    end
  end
end
