# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cdpss < Formula
  desc "A web page screenshot tool with parallel multi-URL capture and lock-free Chrome profile support, powered by chromedp (headless Chrome). Only Chrome is required — no Puppeteer, no Playwright, no Node.js, no Python."
  homepage "https://github.com/xshoji/chromedp-screenshots"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.1/chromedp-screenshots_0.0.1_macOS_x86_64.zip"
      sha256 "9c5605694f5ab6cb6cf75a6a614f5ffef4c8d6f6306cf7682f551fd59d954bb2"

      define_method(:install) do
        bin.install "cdpss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.1/chromedp-screenshots_0.0.1_macOS_arm64.zip"
      sha256 "35f342da69ebd2d38814b630d88672906dc50bf489880010b61a47c65fc69be2"

      define_method(:install) do
        bin.install "cdpss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.1/chromedp-screenshots_0.0.1_Linux_x86_64.zip"
      sha256 "57213e7ef93e8c18834bb29949d82edb055977fc7490470726ae81a56d627d2e"
      define_method(:install) do
        bin.install "cdpss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.1/chromedp-screenshots_0.0.1_Linux_arm64.zip"
      sha256 "71d3a56e9ea8fdeba18646c3761285c9dec24e27a423072b6d12d23fdf5124b1"
      define_method(:install) do
        bin.install "cdpss"
      end
    end
  end
end
