# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cds < Formula
  desc "A web page screenshot tool with parallel multi-URL capture and lock-free Chrome profile support, powered by chromedp (headless Chrome). Only Chrome is required — no Puppeteer, no Playwright, no Node.js, no Python."
  homepage "https://github.com/xshoji/chromedp-screenshots"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.6/chromedp-screenshots_0.0.6_macOS_x86_64.zip"
      sha256 "cfe26de151aef2ff85344e8fd965a17a9356eb1caed0d5292202049a5f968e28"

      define_method(:install) do
        bin.install "cds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.6/chromedp-screenshots_0.0.6_macOS_arm64.zip"
      sha256 "753e437b7964eff396550699c25d74f1e17c09a649d2687770199f7acc8e0250"

      define_method(:install) do
        bin.install "cds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.6/chromedp-screenshots_0.0.6_Linux_x86_64.zip"
      sha256 "15ff6463b5421dffd0926a4a2dcd03b07e47085ef18561e5d2c9b311a24836f9"
      define_method(:install) do
        bin.install "cds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.6/chromedp-screenshots_0.0.6_Linux_arm64.zip"
      sha256 "6ee9e29d64ab9a4e20c0855706e11e6046215d3ee71c2ff9662e4d07b6da90cd"
      define_method(:install) do
        bin.install "cds"
      end
    end
  end
end
