# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cds < Formula
  desc "A web page screenshot tool with parallel multi-URL capture and lock-free Chrome profile support, powered by chromedp (headless Chrome). Only Chrome is required — no Puppeteer, no Playwright, no Node.js, no Python."
  homepage "https://github.com/xshoji/chromedp-screenshots"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.4/chromedp-screenshots_0.0.4_macOS_x86_64.zip"
      sha256 "565c1835f15e718e71f84c2ceff2e59951843680caee20d3442b1a8af5ba28af"

      define_method(:install) do
        bin.install "cds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.4/chromedp-screenshots_0.0.4_macOS_arm64.zip"
      sha256 "46f4e1124bc8dbf4724214cb98b2c2bf64bc93746de2c9740e79f1ee42d2077b"

      define_method(:install) do
        bin.install "cds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.4/chromedp-screenshots_0.0.4_Linux_x86_64.zip"
      sha256 "a3267acdca53a6ee00bcde02b124cbe670d6289cd72ccd5681569853d5d8476c"
      define_method(:install) do
        bin.install "cds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.4/chromedp-screenshots_0.0.4_Linux_arm64.zip"
      sha256 "09e5df99ccb74c6745d723487b200c08c5e5e9fd119e4272468c2e6d6b91f9c3"
      define_method(:install) do
        bin.install "cds"
      end
    end
  end
end
