# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cds < Formula
  desc "A web page screenshot tool with parallel multi-URL capture and lock-free Chrome profile support, powered by chromedp (headless Chrome). Only Chrome is required — no Puppeteer, no Playwright, no Node.js, no Python."
  homepage "https://github.com/xshoji/chromedp-screenshots"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.5/chromedp-screenshots_0.0.5_macOS_x86_64.zip"
      sha256 "2f2d3222250e7793f6779e6ceaa819a379b11936e7572098edd58cbcd9e34cfc"

      define_method(:install) do
        bin.install "cds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.5/chromedp-screenshots_0.0.5_macOS_arm64.zip"
      sha256 "5652c90e1fae6e5098250ef9b4531126cd13c1acb3ee4ae7d7ae5a6e3afc6111"

      define_method(:install) do
        bin.install "cds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.5/chromedp-screenshots_0.0.5_Linux_x86_64.zip"
      sha256 "93c46bd805a013de724830522211eacec50cfa777fe5c36ce89a2503036bd836"
      define_method(:install) do
        bin.install "cds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.5/chromedp-screenshots_0.0.5_Linux_arm64.zip"
      sha256 "f3b5f5a95a7d4bc58e4438dd6abb7117e0a5f5f6b36d5114dac3e8734e8d424c"
      define_method(:install) do
        bin.install "cds"
      end
    end
  end
end
