# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cps < Formula
  desc "A web page screenshot tool with parallel multi-URL capture and lock-free Chrome profile support, powered by chromedp (headless Chrome). Only Chrome is required — no Puppeteer, no Playwright, no Node.js, no Python."
  homepage "https://github.com/xshoji/chromedp-screenshots"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.3/chromedp-screenshots_0.0.3_macOS_x86_64.zip"
      sha256 "5ff2b6990a67bf16b22011c9a5f4a879ec969acccc1de4814c662dacf2448f1b"

      define_method(:install) do
        bin.install "cps"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.3/chromedp-screenshots_0.0.3_macOS_arm64.zip"
      sha256 "59d6b9345ac16a03d0c8247b6878d719269d807c8b0954aab7e2c6b8442fcee7"

      define_method(:install) do
        bin.install "cps"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.3/chromedp-screenshots_0.0.3_Linux_x86_64.zip"
      sha256 "b1ba8c73f5f03f1b3eb0f9e04ab051b0a57455604f01485860e61cd5f7efed90"
      define_method(:install) do
        bin.install "cps"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.3/chromedp-screenshots_0.0.3_Linux_arm64.zip"
      sha256 "c21165768e8c6de482f234f2f004e622d8910a10c16a4c64de362bb85c5426f0"
      define_method(:install) do
        bin.install "cps"
      end
    end
  end
end
