# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cps < Formula
  desc "A web page screenshot tool with parallel multi-URL capture and lock-free Chrome profile support, powered by chromedp (headless Chrome). Only Chrome is required — no Puppeteer, no Playwright, no Node.js, no Python."
  homepage "https://github.com/xshoji/chromedp-screenshots"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.2/chromedp-screenshots_0.0.2_macOS_x86_64.zip"
      sha256 "71f3bb200b6a0c70a033c9af9e3e32b8b40c0e9e974ef9eff3b0bef871e66695"

      define_method(:install) do
        bin.install "cps"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.2/chromedp-screenshots_0.0.2_macOS_arm64.zip"
      sha256 "c96ccb29c6d2c20076c7a1739fe25df68bbaed9f3b57d006599a2d1b3024bd69"

      define_method(:install) do
        bin.install "cps"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.2/chromedp-screenshots_0.0.2_Linux_x86_64.zip"
      sha256 "6e8cc33ae204d96cd8adc5121495dbd15acaa67bf895b225d4f74ef685f5ee12"
      define_method(:install) do
        bin.install "cps"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.2/chromedp-screenshots_0.0.2_Linux_arm64.zip"
      sha256 "a75b6e68f24936deb026aedca6ca64a1f58f6f6e95f592cb2f45779741776e90"
      define_method(:install) do
        bin.install "cps"
      end
    end
  end
end
