# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cps < Formula
  desc "A web page screenshot tool with parallel multi-URL capture and lock-free Chrome profile support, powered by chromedp (headless Chrome). Only Chrome is required — no Puppeteer, no Playwright, no Node.js, no Python."
  homepage "https://github.com/xshoji/chromedp-screenshots"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.1/chromedp-screenshots_0.0.1_macOS_x86_64.zip"
      sha256 "c0a1d28266d922995b7856ae3b823a75e9b379650692752b61df42eb1dd8580b"

      define_method(:install) do
        bin.install "cps"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.1/chromedp-screenshots_0.0.1_macOS_arm64.zip"
      sha256 "7dc8acc23a947823f85f5bf2dcc4c652117efeefad7404b2a110741d69bdd24a"

      define_method(:install) do
        bin.install "cps"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.1/chromedp-screenshots_0.0.1_Linux_x86_64.zip"
      sha256 "c3f84da0214159b1e251569ace5920a4271c06e92b4e2021f34c29975f4d1cda"
      define_method(:install) do
        bin.install "cps"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/chromedp-screenshots/releases/download/v0.0.1/chromedp-screenshots_0.0.1_Linux_arm64.zip"
      sha256 "53755ca77b1352e2cde25b39174bd32a8189b945ad12599c234fdcf09c1ebc44"
      define_method(:install) do
        bin.install "cps"
      end
    end
  end
end
