# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imgdiff < Formula
  desc "Detect and visualize differences between two images"
  homepage "https://github.com/xshoji/go-img-diff"
  version "0.0.6"

  on_macos do
    url "https://github.com/xshoji/go-img-diff/releases/download/v0.0.6/go-img-diff_0.0.6_macOS_x86_64.zip"
    sha256 "8969d6944e95230757d6d0ab3373d878aec3e912673faf6333f36a3f5c394021"

    define_method(:install) do
      bin.install "imgdiff"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Imgdiff
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/go-img-diff/releases/download/v0.0.6/go-img-diff_0.0.6_Linux_x86_64.zip"
      sha256 "9f35d2925375405c7d87286722b3e0f475d198e6e53fd728ff64187801b8eaff"
      define_method(:install) do
        bin.install "imgdiff"
      end
    end
  end
end
