# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Imgdiff < Formula
  desc "Detect and visualize differences between two images"
  homepage "https://github.com/xshoji/go-img-diff"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xshoji/go-img-diff/releases/download/v0.1.0/go-img-diff_0.1.0_macOS_x86_64.zip"
      sha256 "c96facb8982f3c942d59c12fae7433e88ec6f273201765893150cbf5effa1239"

      define_method(:install) do
        bin.install "imgdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xshoji/go-img-diff/releases/download/v0.1.0/go-img-diff_0.1.0_macOS_arm64.zip"
      sha256 "cc93c84e41fafcf397ea8465494098166f237623b7e6aa78191e4b26c2215c17"

      define_method(:install) do
        bin.install "imgdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/go-img-diff/releases/download/v0.1.0/go-img-diff_0.1.0_Linux_x86_64.zip"
      sha256 "5a5c0d979b4016112f115584d4bde4ad6efcc58fc7ea70ba39ba8af7214b48e1"
      define_method(:install) do
        bin.install "imgdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/go-img-diff/releases/download/v0.1.0/go-img-diff_0.1.0_Linux_arm64.zip"
      sha256 "5d2edeca5c474feefc2a8dd342fb0f46b7fa781d9165549ef858867ba18c473b"
      define_method(:install) do
        bin.install "imgdiff"
      end
    end
  end
end
