# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sesnap < Formula
  desc "A web page screenshot tool with parallel multi-URL capture and lock-free Chrome profile support, powered by chromedp (headless Chrome). Only Chrome is required — no Puppeteer, no Playwright, no Node.js, no Python."
  homepage "https://github.com/xshoji/sesnap"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xshoji/sesnap/releases/download/v0.2.0/sesnap_0.2.0_macOS_x86_64.zip"
      sha256 "9c2ce086aea3966791ee490c81419db756541ebaf9a216041bbc12612630bf0c"

      define_method(:install) do
        bin.install "sesnap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xshoji/sesnap/releases/download/v0.2.0/sesnap_0.2.0_macOS_arm64.zip"
      sha256 "498911f885bf6d235c577133759ec4d33ebea9dad7ea7445765cbdcb422fee7c"

      define_method(:install) do
        bin.install "sesnap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/sesnap/releases/download/v0.2.0/sesnap_0.2.0_Linux_x86_64.zip"
      sha256 "0782ef3b5f6de86efcad4f8bc271ff8a210cdaf595eefb1d0aa1b6d5e6aa23dc"
      define_method(:install) do
        bin.install "sesnap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/sesnap/releases/download/v0.2.0/sesnap_0.2.0_Linux_arm64.zip"
      sha256 "f224e90641cd1e58cad4b0edc2f9da12af80f45cd63ed9d12cf18ed91d48a30c"
      define_method(:install) do
        bin.install "sesnap"
      end
    end
  end
end
