# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sesnap < Formula
  desc "A web page screenshot tool with parallel multi-URL capture and lock-free Chrome profile support, powered by chromedp (headless Chrome). Only Chrome is required — no Puppeteer, no Playwright, no Node.js, no Python."
  homepage "https://github.com/xshoji/sesnap"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xshoji/sesnap/releases/download/v0.1.1/sesnap_0.1.1_macOS_x86_64.zip"
      sha256 "4d849833081d12f3dc3e7274729e601a21c99a533063f41cdac62b8c8502ad38"

      define_method(:install) do
        bin.install "sesnap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xshoji/sesnap/releases/download/v0.1.1/sesnap_0.1.1_macOS_arm64.zip"
      sha256 "0c5cb3e3e76223bc56fe759873535a3700d9b10879d941aafe4a8ed0d2b615a5"

      define_method(:install) do
        bin.install "sesnap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/sesnap/releases/download/v0.1.1/sesnap_0.1.1_Linux_x86_64.zip"
      sha256 "868b2c8caadeadb0616038adda2696d1e1f744ee94baf0f499d5722a0275a883"
      define_method(:install) do
        bin.install "sesnap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/sesnap/releases/download/v0.1.1/sesnap_0.1.1_Linux_arm64.zip"
      sha256 "c260cf9a3cc88fc61321bfe9cad2f82d0051d37f9ed008698efeee46604f6b83"
      define_method(:install) do
        bin.install "sesnap"
      end
    end
  end
end
