# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sesnap < Formula
  desc "A web page screenshot tool with parallel multi-URL capture and lock-free Chrome profile support, powered by chromedp (headless Chrome). Only Chrome is required — no Puppeteer, no Playwright, no Node.js, no Python."
  homepage "https://github.com/xshoji/sesnap"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xshoji/sesnap/releases/download/v0.1.0/sesnap_0.1.0_macOS_x86_64.zip"
      sha256 "ffa41ebcc95e10dbe773925ffa544225e61bb35dc8d40e36160a3b1ed792536b"

      define_method(:install) do
        bin.install "sesnap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xshoji/sesnap/releases/download/v0.1.0/sesnap_0.1.0_macOS_arm64.zip"
      sha256 "02f6eb30ad2e33cbb14987c49e2868e6302f53543cc8057ba1440de95a6f128b"

      define_method(:install) do
        bin.install "sesnap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/sesnap/releases/download/v0.1.0/sesnap_0.1.0_Linux_x86_64.zip"
      sha256 "3cfc8133d07b89b7eceb1c26f5872a825f6a48fa582dcd64e54c265ac5cda78a"
      define_method(:install) do
        bin.install "sesnap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/sesnap/releases/download/v0.1.0/sesnap_0.1.0_Linux_arm64.zip"
      sha256 "d1c85b3f7830c30993fd0e1f541246614c275320474dc5a78d71723c67e6028b"
      define_method(:install) do
        bin.install "sesnap"
      end
    end
  end
end
