# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sitesnap < Formula
  desc "A web page screenshot tool with parallel multi-URL capture and lock-free Chrome profile support, powered by chromedp (headless Chrome). Only Chrome is required — no Puppeteer, no Playwright, no Node.js, no Python."
  homepage "https://github.com/xshoji/sitesnap"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xshoji/sitesnap/releases/download/v0.1.0/sitesnap_0.1.0_macOS_x86_64.zip"
      sha256 "de13d1cc18b7c0f3b524ffeb5aa4b84e2538e063e2e2fa2bbbbfa4040e18389f"

      define_method(:install) do
        bin.install "sitesnap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xshoji/sitesnap/releases/download/v0.1.0/sitesnap_0.1.0_macOS_arm64.zip"
      sha256 "a13c3a04d9baf41655788a4c899abda15ea4ae2dbd22f498fcc2081cb6ef6cdc"

      define_method(:install) do
        bin.install "sitesnap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/sitesnap/releases/download/v0.1.0/sitesnap_0.1.0_Linux_x86_64.zip"
      sha256 "44f29080b8eb8504e4b45b03c5d10cca770a6dc0e4b6bb7d9f6b1b5bb0ed5c2a"
      define_method(:install) do
        bin.install "sitesnap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xshoji/sitesnap/releases/download/v0.1.0/sitesnap_0.1.0_Linux_arm64.zip"
      sha256 "b1ce26ca9fe3954977e0af2a27b5a105fe1df6e60be1eef2335ba1530c78bb6b"
      define_method(:install) do
        bin.install "sitesnap"
      end
    end
  end
end
